apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
    - image: dialloabdourahman/auth-ticketing
      context: auth
      docker:
        dockerfile: Dockerfile
    - image: dialloabdourahman/tickets-ticketing
      context: tickets
      docker:
        dockerfile: Dockerfile
    - image: dialloabdourahman/orders-ticketing
      context: orders
      docker:
        dockerfile: Dockerfile
    - image: dialloabdourahman/expiration-ticketing
      context: expiration
      docker:
        dockerfile: Dockerfile
    - image: dialloabdourahman/payments-ticketing
      context: payments
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/dev/auth-depl.yaml
    - infra/k8s/dev/auth-mongo-depl.yaml
    - infra/k8s/dev/ingress-srv.yaml
    - infra/k8s/dev/tickets-depl.yaml
    - infra/k8s/dev/tickets-mongo-depl.yaml
    - infra/k8s/dev/orders-depl.yaml
    - infra/k8s/dev/orders-mongo-depl.yaml
    - infra/k8s/dev/rabbitmq-depl.yaml
    - infra/k8s/dev/expiration-depl.yaml
    - infra/k8s/dev/expiration-redis-depl.yaml
    - infra/k8s/dev/payments-depl.yaml
    - infra/k8s/dev/payments-mongo-depl.yaml
