name: build-deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build the docker image
        run: cd auth && docker build -t dialloabdourahman/auth-ticketing:latest .
      
      - name: Login to dockerhub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push the image to dockerhub
        run: docker push dialloabdourahman/auth-ticketing:latest
          
