name: deploy-infra

on:
  push:
    branches:
      - main
    paths:
      - "infra/k8s/prod/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to dockerhub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save $DIGITAL_OCEAN_CLUSTER_NAME
        env:
          DIGITAL_OCEAN_CLUSTER_NAME: ${{ secrets.DIGITAL_OCEAN_CLUSTER_NAME }}

      - name: Apply the deployments
        run: kubectl apply -f infra/k8s/prod

