name: tests-auth

on:
  pull_request:
    branches:
      - main
    paths:
      - "auth/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' 

      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: '7.0' 
      
      - name: Install dependencies and run tests
        run: cd auth && npm install && npm run test:ci
